//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecop2.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaEcopEntities : DbContext
    {
        public PruebaEcopEntities()
            : base("name=PruebaEcopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PEDIDO_CABECERA> PEDIDO_CABECERA { get; set; }
        public virtual DbSet<PEDIDO_DETALLE> PEDIDO_DETALLE { get; set; }
        public virtual DbSet<ESTADO_PEDIDO> ESTADO_PEDIDO { get; set; }
    }
}
