//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecop2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_CABECERA
    {
        public int PEDIDO_ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public Nullable<double> CANTIDAD_TOTAL { get; set; }
        public Nullable<decimal> PRECIO_TOTAL { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    }
}
