USE [PruebaEcop]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 26/5/2024 22:49:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[CLIENTE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NRO_DOCUMENTO] [varchar](12) NULL,
	[TIPO_DOCUMENTO] [varchar](20) NULL,
	[RAZON_SOCIAL] [varchar](200) NULL,
	[DIRECCION] [varchar](200) NULL,
	[NRO_TELEFONO] [varchar](50) NULL,
	[FECHA_INGRESO] [date] NULL,
	[CORREO] [varchar](50) NULL,
	[CIUDAD] [varchar](200) NULL,
	[BARRIO] [varchar](200) NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CLIENTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


